services:
  mongo:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_DATABASE: productreviews
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    ports:
      - "5500:5500"
    command: ["npm", "run", "dev"]

  frontend:
    build: ./frontend
    restart: always
    environment:
      - VITE_API_URL=http://localhost:5500/api
    ports:
      - "5173:5173"
    depends_on:
      - backend
    command: ["npm", "run", "dev"]

volumes:
  mongo-data:
